version: "3"
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      -  3000:3000
    container_name: frontend
    networks:
      -  quizandlearn-net
    volumes:
      -  ./frontend/src:/usr/app/src
      -  ./frontend/public:/usr/app/public
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    container_name: backend
    networks:
      - quizandlearn-net
    volumes:
      - ./backend/src:/usr/app/src
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - quizandlearn-net
    volumes:
      - mongo-data:/data/db

networks:
  quizandlearn-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
